# Generated by Django 6.0.2 on 2026-05-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='medicament',
            name='code_barre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
