# Generated by Django 6.0.5 on 2026-06-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0002_remove_medicament_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(default='#0C447C', max_length=10)),
                ('icone', models.CharField(default='bi-capsule', max_length=30)),
                ('emplacement', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Étagère',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='medicament',
            name='etagere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaments', to='medicaments.etagere'),
        ),
    ]
