# Generated by Django 6.0.5 on 2026-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0003_etagere_medicament_etagere'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicaments/', verbose_name='Photo du médicament'),
        ),
    ]
