# Generated by Django 6.0.5 on 2026-07-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('carte', 'Carte bancaire')], default='especes', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué')], default='paye', max_length=20),
        ),
    ]
