# Generated by Django 6.0.5 on 2026-09-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_add_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='motif_annulation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vente',
            name='secret_webhook',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
