# Generated by Codex on 2026-06-02

from django.db import migrations, models


def set_existing_roles(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for profile in UserProfile.objects.select_related('user'):
        if profile.user.is_staff or profile.user.is_superuser:
            profile.role = 'patron'
        else:
            profile.role = 'caissier'
        profile.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('patron', 'Patron'),
                    ('pharmacien', 'Pharmacien'),
                    ('caissier', 'Caissier'),
                ],
                default='caissier',
                max_length=20,
            ),
        ),
        migrations.RunPython(set_existing_roles, migrations.RunPython.noop),
    ]
