# Generated by Django 6.0.5 on 2026-06-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
        ('accounts', '0002_userprofile_role'),
    ]

    operations = [
    ]
