# Generated by Django 6.0.2 on 2026-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pharmacie', models.CharField(default='PharmaGest', max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
            ],
            options={
                'verbose_name': 'Paramètres',
            },
        ),
    ]
