# Generated by Django 6.0.2 on 2026-05-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='couleur',
            field=models.CharField(default='#0F6E56', max_length=10),
        ),
        migrations.AddField(
            model_name='parametres',
            name='format_date',
            field=models.CharField(default='d/m/Y', max_length=20),
        ),
        migrations.AddField(
            model_name='parametres',
            name='langue',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='parametres',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='parametres',
            name='session_duree',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='parametres',
            name='tentatives_max',
            field=models.IntegerField(default=5),
        ),
    ]
