# Generated by Django 6.0.5 on 2026-06-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_parametres_couleur_parametres_format_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
