# Generated by Django 6.0.5 on 2026-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_alter_parametres_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
